
resources:
- name: my-pipeline
  type: git
  source:
    uri: {{github_url}}
    username: {{github_token}}

jobs:

- name: test-ssh
  plan:
  - aggregate:
    - get: my-pipeline
  - task: SSH-and-SCP
    file: my-pipeline/pipes/task.yml
    params:
      OPSMAN_IP: {{opsman_ip}}
      SSHPASS: {{opsman_ssh_password}}
      CERT: {{cert}}
      KEY: {{key}}
